bar = "pound_force_per_square_inch / 14.504"
pascal = "pound_force_per_square_inch * 6895"
pound_force_per_square_inch = "pound_force_per_square_inch"
standard_atmosphere = "pound_force_per_square_inch / 14.696"
torr = "pound_force_per_square_inch * 51.715"
