degree = "minute_of_arc / 60"
gradian = "minute_of_arc / 54"
milliradian = "minute_of_arc * 1000*pi/(60 * 180)"
minute_of_arc = "minute_of_arc"
radian = "minute_of_arc * pi/(60 * 180)"
second_of_arc = "minute_of_arc * 60"
