square_kilometer = "square_meter / 1e+6"
square_meter = "square_meter"
square_mile = "square_meter / 2.59e+6"
square_yard = "square_meter * 1.196"
square_foot = "square_meter * 10.764"
square_inch = "square_meter * 1550"
hectare = "square_meter / 10000"
acre = "square_meter / 4047"
